#!/usr/bin/env python3

"""Example that rotates servos on every channel to 180 and then back to 0."""
import time
from adafruit_servokit import ServoKit
import random
from random import seed
from random import randint

seed(1)

# Set channels to the number of servo channels on your kit.
kit = ServoKit(channels=16)
servo_idx = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

while True:
    start = 0
    end = randint(0, 180)
    num = randint(0, 16)

    # chose a random sampling of unique servos
    sampling = random.sample(servo_idx, k=num)
    # print(sampling)

    for i in range(len(sampling)):
        kit.servo[sampling[i]].angle = end
    time.sleep(0.25)
    
    for i in range(len(sampling)):
        kit.servo[sampling[i]].angle = start
    time.sleep(0.15)
