#!/usr/bin/env python3

"""Example that rotates servos on every channel to 180 and then back to 0."""
import time
from adafruit_servokit import ServoKit
import random
from random import seed
from random import randint

seed(1)

# Set channels to the number of servo channels on your kit.
kit = ServoKit(channels=16)

while True:
    start = 0
    end = randint(0, 180)
    num = randint(0, 16)

    # chose a random sampling of unique servos
    sampling = random.sample(len(kit.servo), k=num)
    # print(sampling)

    for i in range(len(sampling)):
        kit.servo[sampling[i]].angle = end
    time.sleep(0.5)
    
    for i in range(len(sampling)):
        kit.servo[sampling[i]].angle = start
    time.sleep(2)


